config/routes.rb
Rails.application.routes.draw do
  #get 'admin/index'

  resources :contents
  root 'main#index'

  # get "/login" => "clearance/sessions#new", as: "sign_in"
  # get "/welcome" => "clearance/users#new", as: "sign_up"
  # # get "/sign_up" => "clearance/users#new", as: "sign_up"
  # get '/logout' => 'clearance/sessions#destroy', as: 'sign_out'

  get "/admin" => "admin#index", as: 'admin_section'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :require_login
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:name, :prettyName, :content, :previousContent, :displayTitle)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :content_name %>
  </div>

  <div class="field">
    <%= form.label :prettyName %>
    <%= form.text_field :prettyName, id: :content_prettyName %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :content_content %>
  </div>

  <div class="field">
    <%= form.label :previousContent %>
    <%= form.text_area :previousContent, id: :content_previousContent %>
  </div>

  <div class="field">
    <%= form.label :displayTitle %>
    <%= form.check_box :displayTitle, id: :content_displayTitle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Editing Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prettyname</th>
      <th>Content</th>
      <th>Previouscontent</th>
      <th>Displaytitle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.name %></td>
        <td><%= content.prettyName %></td>
        <td><%= content.content %></td>
        <td><%= content.previousContent %></td>
        <td><%= content.displayTitle %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= render 'form', content: @content %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<p>
  <strong>Prettyname:</strong>
  <%= @content.prettyName %>
</p>

<p>
  <strong>Content:</strong>
  <%= @content.content %>
</p>

<p>
  <strong>Previouscontent:</strong>
  <%= @content.previousContent %>
</p>

<p>
  <strong>Displaytitle:</strong>
  <%= @content.displayTitle %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Highland Brass Co.</title>
	<%= csrf_meta_tags %>
	
	<%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<meta name="author" content="SemiColonWeb"/>
	
	<!-- Stylesheets
	============================================= -->
	<link href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="css/bootstrap.css" type="text/css"/>
	<link rel="stylesheet" href="style.css" type="text/css"/>
	<link rel="stylesheet" href="css/dark.css" type="text/css"/>
	<link rel="stylesheet" href="css/font-icons.css" type="text/css"/>
	<link rel="stylesheet" href="css/animate.css" type="text/css"/>
	<link rel="stylesheet" href="css/magnific-popup.css" type="text/css"/>
	
	<link rel="stylesheet" href="css/responsive.css" type="text/css"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>
	<!--[if lt IE 9]>
	<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
	<![endif]-->
	
	<!-- SLIDER REVOLUTION 5.x CSS SETTINGS -->
	<link rel="stylesheet" type="text/css" href="include/rs-plugin/css/settings.css" media="screen"/>
	<link rel="stylesheet" type="text/css" href="include/rs-plugin/css/layers.css">
	<link rel="stylesheet" type="text/css" href="include/rs-plugin/css/navigation.css">
	
	<style>
		
		.revo-slider-emphasis-text {
			font-size: 64px;
			font-weight: 700;
			letter-spacing: -1px;
			font-family: 'Raleway', sans-serif;
			padding: 15px 20px;
			border-top: 2px solid #FFF;
			border-bottom: 2px solid #FFF;
		}
		
		.revo-slider-desc-text {
			font-size: 20px;
			font-family: 'Lato', sans-serif;
			width: 650px;
			text-align: center;
			line-height: 1.5;
		}
		
		.revo-slider-caps-text {
			font-size: 16px;
			font-weight: 400;
			letter-spacing: 3px;
			font-family: 'Raleway', sans-serif;
		}
		
		.tp-video-play-button {
			display: none !important;
		}
		
		.tp-caption {
			white-space: nowrap;
		}
	
	</style>
	
	<!-- RAILS STYLESHEETS-->
	<%#= stylesheet_link_tag "bootstrap.css" %>
	<%#= stylesheet_link_tag "style.css" %>
	<%#= stylesheet_link_tag "dark.css" %>
	<%#= stylesheet_link_tag "font-icons.css" %>
	<%#= stylesheet_link_tag "magnific-popup.css" %>
	<%#= stylesheet_link_tag "responsive.css" %>
	<!--<meta name="viewport" content="width=device-width, initial-scale=1"/>-->
	<!-- SLIDER REVOLUTION 5.x CSS SETTINGS -->
	<%#= stylesheet_link_tag "settings.css", media: "all" %>
	<%#= stylesheet_link_tag "layers.css" %>
	<%#= stylesheet_link_tag "navigation.css" %>

</head>

<body class="stretched">

<%= yield %>

<%= javascript_include_tag "jquery.js" %>
<%= javascript_include_tag "plugins.js" %>
<%= javascript_include_tag "functions.js" %>

<!-- SLIDER REVOLUTION 5.x SCRIPTS  -->
<%= javascript_include_tag "jquery.themepunch.tools.min.js" %>
<%= javascript_include_tag "jquery.themepunch.revolution.min.js" %>

<%= javascript_include_tag "revolution.extension.video.min.js" %>
<%= javascript_include_tag "revolution.extension.slideanims.min.js" %>
<%= javascript_include_tag "revolution.extension.actions.min.js" %>
<%= javascript_include_tag "revolution.extension.layeranimation.min.js" %>
<%= javascript_include_tag "revolution.extension.kenburn.min.js" %>
<%= javascript_include_tag "revolution.extension.navigation.min.js" %>
<%= javascript_include_tag "revolution.extension.migration.min.js" %>
<%= javascript_include_tag "revolution.extension.parallax.min.js" %>

<script type="text/javascript">
	
	var tpj = jQuery;
	tpj.noConflict();
	
	tpj(document).ready(function () {
		
		var apiRevoSlider = tpj('.tp-banner').show().revolution(
			{
				sliderType: "standard",
				jsFileLocation: "include/rs-plugin/js/",
				dottedOverlay: "none",
				delay: 16000,
				startwidth: 1140,
				startheight: 600,
				hideThumbs: 200,
				
				thumbWidth: 100,
				thumbHeight: 50,
				thumbAmount: 5,
				
				navigation: {
					keyboardNavigation: "on",
					keyboard_direction: "horizontal",
					mouseScrollNavigation: "off",
					onHoverStop: "off",
					touch: {
						touchenabled: "on",
						swipe_threshold: 75,
						swipe_min_touches: 1,
						swipe_direction: "horizontal",
						drag_block_vertical: false
					},
					thumbnails: {
						style: "hesperiden",
						enable: true,
						width: 100,
						height: 50,
						min_width: 100,
						wrapper_padding: 5,
						wrapper_color: "#ffffff",
						wrapper_opacity: "0.5",
						tmp: '<span class="tp-thumb-image"></span><span class="tp-thumb-title">{{title}}</span>',
						visibleAmount: 5,
						hide_onmobile: false,
						hide_onleave: false,
						direction: "horizontal",
						span: false,
						position: "inner",
						space: 5,
						h_align: "right",
						v_align: "bottom",
						h_offset: 20,
						v_offset: 50
					}
				},
				
				touchenabled: "on",
				onHoverStop: "on",
				
				swipe_velocity: 0.7,
				swipe_min_touches: 1,
				swipe_max_touches: 1,
				drag_block_vertical: false,
				
				parallax: "mouse",
				parallaxBgFreeze: "on",
				parallaxLevels: [7, 4, 3, 2, 5, 4, 3, 2, 1, 0],
				
				keyboardNavigation: "off",
				
				navigationHAlign: "center",
				navigationVAlign: "bottom",
				navigationHOffset: 0,
				navigationVOffset: 20,
				
				soloArrowLeftHalign: "left",
				soloArrowLeftValign: "center",
				soloArrowLeftHOffset: 20,
				soloArrowLeftVOffset: 0,
				
				soloArrowRightHalign: "right",
				soloArrowRightValign: "center",
				soloArrowRightHOffset: 20,
				soloArrowRightVOffset: 0,
				
				shadow: 0,
				fullWidth: "off",
				fullScreen: "on",
				
				spinner: "spinner4",
				
				stopLoop: "off",
				stopAfterLoops: -1,
				stopAtSlide: -1,
				
				shuffle: "off",
				
				autoHeight: "off",
				forceFullWidth: "off",
				
				
				hideThumbsOnMobile: "off",
				hideNavDelayOnMobile: 1500,
				hideBulletsOnMobile: "off",
				hideArrowsOnMobile: "off",
				hideThumbsUnderResolution: 0,
				
				hideSliderAtLimit: 0,
				hideCaptionAtLimit: 0,
				hideAllCaptionAtLilmit: 0,
				startWithSlide: 0,
			});
		
	});

</script><!-- END REVOLUTION SLIDER -->


</body>
</html>

app/views/main/_feature.html.erb
<div class="container bottommargin clearfix">
	
	<div class="col_one_third nobottommargin">
		<div class="feature-box media-box">
			<div class="fbox-media">
				<img src="images/stock4-thumbnail.jpg" alt="Why choose Us?">
			</div>
			<div class="fbox-desc">
				<h3>The Best Drinks.<span class="subtitle">Come Have One On the House!</span></h3>
				<p>Best Drinks 1.</p>
			</div>
		</div>
	</div>
	
	<div class="col_one_third nobottommargin">
		<div class="feature-box media-box">
			<div class="fbox-media">
				<img src="images/stock5-thumbnail.jpg" alt="Why choose Us?">
			</div>
			<div class="fbox-desc">
				<h3>Your favorite Cocktails.<span class="subtitle">Come have Dim make you one!</span></h3>
				<p>He's good</p>
			</div>
		</div>
	</div>
	
	<div class="col_one_third nobottommargin col_last">
		<div class="feature-box media-box">
			<div class="fbox-media">
				<img src="images/stock6-thumbnail.jpg" alt="Why choose Us?">
			</div>
			<div class="fbox-desc">
				<h3>The Best Athmosphere.<span class="subtitle">Come and Relax.</span></h3>
				<p>Come relax with us.</p>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>

app/views/main/_feature2.html.erb
<div class="container clearfix">
	
	<div class="col_one_third nobottommargin topmargin">
		<div class="feature-box fbox-center fbox-plain nobottomborder">
			<div class="fbox-icon">
				<a href="#"><img src="images/icons/restaurant/glass.png" alt="Icon" data-animate="zoomIn"></a>
			</div>
			<h3>World Class Cocktails<span class="subtitle">Famous Recipe's</span></h3>
		</div>
	</div>
	
	<div class="col_one_third nobottommargin topmargin">
		<div class="feature-box fbox-center fbox-plain nobottomborder">
			<div class="fbox-icon">
				<a href="#"><img src="images/icons/restaurant/fork.png" alt="Icon" data-animate="zoomIn" data-delay="200"></a>
			</div>
			<h3>Great Food<span class="subtitle">The Best In Waterbury</span></h3>
		</div>
	</div>
	
	<div class="col_one_third nobottommargin topmargin col_last">
		<div class="feature-box fbox-center fbox-plain nobottomborder">
			<div class="fbox-icon">
				<a href="#"><img src="images/icons/restaurant/tea.png" alt="Icon" data-animate="zoomIn" data-delay="600"></a>
			</div>
			<h3>Amazing Dining Experience<span class="subtitle">Come, Relax, Enjoy</span></h3>
		</div>
	</div>
	<div class="clear"></div>
</div>

app/views/main/_footer.html.erb
<footer id="footer" class="dark">
	
	<div class="container">
		
		<!-- Footer Widgets
		============================================= -->
		<div class="footer-widgets-wrap clearfix">
			
			<div class="col_full">
				
				<div class="heading-block center nobottommargin">
					<h2>Need to make a Reservation? <strong>Call +165.4455.6254</strong></h2>
				</div>
			
			</div>
		
		</div><!-- .footer-widgets-wrap end -->
	
	</div>
	
	<!-- Copyrights
	============================================= -->
	<div id="copyrights">
		
		<div class="container clearfix">
			
			<div class="col_half">
				Copyrights &copy; 2014 All Rights Reserved by Canvas Inc.<br>
				<% if signed_in? %>
						Signed in as: <%= current_user.email %>
						<%= button_to 'Sign out', sign_out_path, method: :delete %>
				<% else %>
						<%= link_to 'Sign in', sign_in_path %>
				<% end %>
				
				<div id="flash">
					<% flash.each do |key, value| %>
							<div class="flash <%= key %>"><%= value %></div>
					<% end %>
				</div>
				<div class="copyright-links"><a href="#">Terms of Use</a> / <a href="#">Privacy Policy</a></div>
			</div>
			
			<div class="col_half col_last tright">
				<div class="fright clearfix">
					<a href="#" class="social-icon si-small si-borderless si-facebook">
						<i class="icon-facebook"></i>
						<i class="icon-facebook"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-twitter">
						<i class="icon-twitter"></i>
						<i class="icon-twitter"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-gplus">
						<i class="icon-gplus"></i>
						<i class="icon-gplus"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-pinterest">
						<i class="icon-pinterest"></i>
						<i class="icon-pinterest"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-vimeo">
						<i class="icon-vimeo"></i>
						<i class="icon-vimeo"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-github">
						<i class="icon-github"></i>
						<i class="icon-github"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-yahoo">
						<i class="icon-yahoo"></i>
						<i class="icon-yahoo"></i>
					</a>
					
					<a href="#" class="social-icon si-small si-borderless si-linkedin">
						<i class="icon-linkedin"></i>
						<i class="icon-linkedin"></i>
					</a>
				</div>
				
				<div class="clear"></div>
			
			</div>
		
		</div>
	
	</div><!-- #copyrights end -->

</footer><!-- #footer end -->

app/views/main/_header.html.erb
<header id="header" class="transparent-header dark full-header" data-sticky-class="not-dark">
	
	<div id="header-wrap">
		
		<div class="container clearfix">
			
			<div id="primary-menu-trigger"><i class="icon-reorder"></i></div>
			
			<!-- Logo
			============================================= -->
			<div id="logo">
				<a href="<%= root_url %>" class="standard-logo inline" data-dark-logo="images/logo-white.JPG">
					<img class="inline-block" src="images/logo-white.JPG" alt="Highland Brass Logo">
				Highland Brass Co.</a>
			</div><!-- #logo end -->
			
			<nav id="primary-menu">
				
				<ul class="norightborder norightpadding norightmargin">
					<li class="current"><a href="#"><div><i class="icon-home2"></i>Home</div></a></li>
					<li><a href="#"><div><i class="icon-file-alt"></i>Menu</div></a></li>
					<li><a href="#"><div><i class="icon-users2"></i>About</div></a></li>
					<li><a href="#"><div><i class="icon-th"></i>Demos</div></a></li>
				</ul>
			
			</nav><!-- #primary-menu end -->
		
		</div>
	
	</div>

</header><!-- #header end -->

app/views/main/_video.html.erb
<div class="section dark" style="margin-top:0px; height: 500px;">
	<div class="container center clearfix vertical-middle">
		<i class="i-plain i-xlarge divcenter bottommargin"></i>
		<div class="slider-caption slider-caption-center">
		</div>
	</div>
	<div class="video-wrap">
		<video poster="images/videos/explore.jpg" preload="auto" loop autoplay muted>
			<source src='images/videos/dimitri_video_1.mp4' type='video/mp4'/>
		</video>
		<div class="video-overlay" style="background-color: rgba(0,0,0,0.35);"></div>
	</div>
</div>